###
GET http://localhost:3000/

###
POST http://localhost:3000/api/v1/user/register
Content-Type: application/json
    
{ 
    "nama":"Taufik",
    "email": "taufik@mail.com",
    "password":"taufik123",
    "alamat":"TELUK",
    "role": "ADMIN"
} 

###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json
    
{ 
    "email": "taufik@mail.com",
    "password":"taufik123"
} 

### 
GET http://localhost:3000/api/v1/user/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0YXVmaWtAbWFpbC5jb20iLCJpYXQiOjE3MDU0NzIyMzUsImV4cCI6MTcwNTU1ODYzNX0.NbLd42JDE1ArU_w1hSJJ2DBf8fauac5Ch_wxDlwaGJk